### ISSUE TITLE
Maven Update

### ISSUE THREAD

**Issue by Longri** [blackears/svgSalamander#14]
Can you please upload the latest release 1.1.1 to Maven?

**Comment by don-vip** [comment]
+1, can you please update Maven Central?

**Comment by blackears** [comment]
Well, I just spent a couple of hours rereading the Maven docs, retweaking my Maven build target in ant and trying to upload a new bundle.  I'm getting the error:
```

Artifact upload failed.
Invalid maven artifacts: [lib/svgSalamander-1.1.3-javadoc.jar, lib/svgSalamander-1.1.3-javadoc.jar.asc, lib/svgSalamander-1.1.3-sources.jar, lib/svgSalamander-1.1.3-sources.jar.asc, lib/svgSalamander-1.1.3.jar, lib/svgSalamander-1.1.3.jar.asc]
```

I changed the paths of the generated artifacts a bit to more closely reflect the recommendations that sonatype provides, but otherwise it is unchanged.

If anyone wants to look at my maven publish process and can recommend changes, please take a look at the maven-publish task that I've put in the build.xml file.

I have very little motivation for getting this working with Maven.  I am very busy and Maven's opaqueness makes updating the archive very difficult.

Honestly, I've had more fun doing my taxes than trying to deal with Maven.  What a crappy, unintuitive and overly complicated system.
