### ISSUE TITLE
Compliance?

### ISSUE THREAD

**Issue by hrj** [blackears/svgSalamander#6]
Hello!

I am very interested in using svgSalamnder for https://github.com/UprootLabs/gngr.

Have you performed any tests to see how many features are covered? I did a quick search on the web. In the answers [here](http://stackoverflow.com/questions/33215722/how-to-use-w3c-svg-test-suite/33226912) there are some hints about running the SVG tests from W3C. The reference images were apparently generated by Batik. So it should be possible to write a script that compares the output from SVGSalamaner and Batik and gives a pass/fail report.

**Comment by blackears** [comment]
Hi,

No, I have not performed systematic testing. I have thought about
it from time to time, but it would be a lot of effort and I cannot
afford the time. I have been updating the source as various people
submit bug reports, so the best I can claim is that for the most part
people are happy with it.

Mark
McKay

-------------------------
SUBJECT: [blackears/svgSalamander]
Compliance? (#6)
DATE: Fri, 14 Oct 2016 08:06:23 -0700
FROM: hrj 
TO:
blackears/svgSalamander 
REPLY-TO: blackears/svgSalamander 

Hello! 

I
am very interested in using svgSalamnder for
https://github.com/UprootLabs/gngr [1]. 

Have you performed any tests
to see how many features are covered? I did a quick search on the web.
In the answers here [2] there are some hints about running the SVG tests
from W3C. The reference images were apparently generated by Batik. So it
should be possible to write a script that compares the output from
SVGSalamaner and Batik and gives a pass/fail report. 

--
You are
receiving this because you are subscribed to this thread.
Reply to this
email directly, view it on GitHub [3], or mute the thread [4].


---
http://www.kitfox.com
  Save

Links:
------
[1]
https://github.com/UprootLabs/gngr
[2]
http://stackoverflow.com/questions/33215722/how-to-use-w3c-svg-test-suite/33226912
[3]
https://github.com/blackears/svgSalamander/issues/6
[4]
